version: 0.0
os: linux
files:
  - source: /
    destination: /coopbot
    
hooks:
  # BeforeInstall:
  #   - location: scripts/install_dependencies.sh
  #     timeout: 300
  #     runas: root

  # AfterInstall:
  #   - location: scripts/change_permissions.sh
  #     timeout: 300
  #     runas: root

  ApplicationStart:
    - location: start.sh
      timeout: 300

  # ApplicationStop:
  #   - location: scripts/stop_server.sh
  #     timeout: 300
  #     runas: root